---
spring:
  profiles: default
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      
message: Hello Message From git repo1 bb
